project:
  title: "Project Title"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utilities/check_packages.R      # install required packages
    - utilities/remove_artifacts.ts   # remove previously constructed files
  render:
    # specify render ordering

author:
  - name: Stepan Polikanov
    orcid: 0000-0002-2329-2750
    email: splknv.public@gmail.com
    attributes:
      corresponding: true
    affiliations:
      - id: uc3m
        name: Universidad Carlos III de Madrid
        department: Social Sciences
  
execute: 
  freeze: false
  warning: false
  error: false
  message: false
  
editor: source


